var airlines=[
    "Adria Airways",
    "Aegean Airlines",
    "Aer Lingus Airlines",
    "Aeroflot Airlines",
    "Aerolineas Argentinas Airlines",
    "Aeromexico Airlines",
    "Africa World Airlines",
    "Aigle Azur",
    "Air Algérie",
    "Air Arabia",
    "Air Astana",
    "Air Austral",
    "Air Baltic",
    "Air Botswana",
    "Air Burkina",
    "Air Cairo",
    "Air Caledonie",
    "Air Canada",
    "Air Caraibes",
    "Air China",
    "Air Corsica",
    "Air Dolomiti",
    "Air Europa",
    "Air France",
    "Air India",
    "Air Italy",
    "Air Koryo",
    "Air Macau",
    "Air Madagascar",
    "Air Malta",
    "Air Mauritius",
    "Air Moldova",
    "Air Namibia",
    "Air New Zealand",
    "Air Niugini Airlines",
    "Air Nostrum Airlines",
    "Air Peace Airline",
    "Air Serbia",
    "Air Seychelles",
    "Air Tahiti",
    "Air Tahiti Nui",
    "Air Transat",
    "Air Vanuatu",
    "AirBridgeCargo Airlines",
    "Aircalin",
    "Airlink",
    "Alaska Airlines",
    "Alitalia Airlines",
    "All Nippon Airways",
    "Allied Air",
    "AlMasria Universal Airlines",
    "American Airlines",
    "Arik Air",
    "Arkia Israeli Airlines",
    "Asiana Airlines",
    "Atlantic Airways",
    "Atlas Air",
    "Atlas Global",
    "Austral Airlines",
    "Austrian Airlines",
    "Avianca Airline",
    "Avianca Brazil",
    "Avianca Costa Rica",
    "Avianca Ecuador Airlines",
    "Avianca Peru",
    "Azerbaijan Airlines",
    "Azores airline",
    "Azul Brazilian airlines",
    "Bahamasair airline",
    "Bangkok Airways",
    "Batik Air",
    "Belavia Belarusian Airlines",
    "BH Air",
    "Biman Bangladesh Airlines",
    "Binter Canarias",
    "Blue air",
    "Blue Panorama airlines",
    "Boliviana de Aviación",
    "Braathens Regional Airlines",
    "British Airways",
    "Brussels Airlines",
    "Bulgaria Air",
    "Bulgaria Air",
    "CAL Cargo Airlines",
    "Camair-Co",
    "Cambodia Angkor Air",
    "Capital Airlines",
    "Cargojet Airways",
    "Cargolux",
    "Caribbean Airlines",
    "Carpatair",
    "Cathay Dragon",
    "Cathay Pacific",
    "Cayman Airways",
    "Chair Airlines AG",
    "China Airlines",
    "China Cargo Airlines",
    "China Eastern Airlines",
    "China Express Airlines",
    "China Express Airlines",
    "China Postal Airlines",
    "China Southern Airlines",
    "CityJet",
    "Comair",
    "Condor Airlines",
    "Congo Airways",
    "Copa Airlines",
    "Corendon Airlines",
    "Corsair International Airlines",
    "Croatia Airlines",
    "Cubana",
    "Cyprus Airways",
    "Czech Airlines",
    "Delta AirLines",
    "DHL Air",
    "DHL Aviation",
    "Eastar Jet",
    "EgyptAir Airline",
    "El Airlines",
    "Emirates",
    "Ethiopian Airlines",
    "Etihad Airways",
    "EuroAtlantic Airways",
    "European Air Transport",
    "Eurowings Airlines",
    "EVA Air",
    "Evelop Airlines",
    "Fiji Airways",
    "Finnair",
    "Flybe Airlines",
    "FlyDubai",
    "FlyDubai",
    "FlyEgypt",
    "Freebird Airlines",
    "Fuzhou Airlines",
    "Garuda Indonesia",
    "Georgian Airways",
    "GOL Linhas Aereas Airlines",
    "Gulf Air",
    "GX Airlines",
    "Hahn Air",
    "Hainan Airlines",
    "Hawaiian Airlines",
    "Hebei Airlines",
    "Hi fly",
    "Hong Kong Air Cargo",
    "Hong Kong Airlines",
    "Hong Kong Express Airways",
    "Iberia",
    "Icelandair",
    "Interjet",
    "Iran Air",
    "Iran Air Tour Airlines",
    "Iran Aseman Airlines",
    "Israir Airlines",
    "Japan Airlines JAL",
    "Jazeera Airways",
    "Jeju Airlines",
    "Jet Airways",
    "Jet Lite",
    "JetBlue Airways",
    "Jin Air",
    "Jordan Aviation",
    "Juneyao Airlines",
    "Kenya Airways",
    "KLM Royal Dutch Airlines",
    "Korean Air",
    "Kunming Airlines",
    "Kuwait Airways",
    "LAM",
    "Lao Airlines",
    "LATAM Airlines Argentina",
    "LATAM Airlines Brasil",
    "LATAM Airlines Colombia",
    "LATAM Airlines Ecuador",
    "LATAM Airlines Group",
    "LATAM Airlines Paraguay",
    "LATAM Airlines Peru",
    "LATAM Cargo Brasil",
    "LATAM Cargo Chile",
    "LIAT Airlines",
    "Loong Air",
    "LOT Polish Airlines",
    "Lucky Air",
    "Lufthansa",
    "Lufthansa Cargo",
    "Lufthansa CityLine",
    "Luxair",
    "Mahan Air",
    "Malaysia Airlines",
    "Malindo Air",
    "Mandarin Airlines",
    "Martinair",
    "Mas Air",
    "Mauritania Airlines International",
    "MIAT Mongolian Airlines",
    "Middle East Airlines",
    "Mistral Air",
    "MNG Airlines",
    "Montenegro Airlines",
    "Myanmar Airways International",
    "NCA Nippon Cargo Airlines",
    "Neos",
    "Nesma Airlines",
    "Nile Air",
    "Nordwind Airlines",
    "Nouvelair",
    "Okay Airways",
    "Olympic Air",
    "Oman Air",
    "Onur Air",
    "Overland Airways",
    "Pegas Fly",
    "Pegasus Airlines",
    "PGA-Portugalia Airlines",
    "Philippine Airlines",
    "PIA Pakistan International Airlines",
    "Precision Air",
    "Qantas",
    "Qatar Airways",
    "Ravn Alaska",
    "Rossiya Airlines",
    "Royal Air Maroc",
    "Royal Brunei Airlines",
    "Royal Jordanian",
    "Rwandair",
    "S7 Airlines",
    "Safair",
    "SATA Air Acores",
    "Saudi Arabian Airlines",
    "SaudiGulf Airlines",
    "Scandinavian Airlines",
    "SCAT Airlines",
    "Shandong Airlines",
    "Shanghai Airlines",
    "Shenzhen Airlines",
    "ShunFeng Airlines",
    "Sichuan Airlines",
    "Silk Way West Airlines",
    "Silkair airlines",
    "Singapore Airlines",
    "SKY Airlines",
    "Smartavia",
    "Solomon Airlines",
    "SOMON AIR",
    "SOUTH AFRICAN AIRWAYS",
    "Sri Lankan Airlines",
    "Sun Express",
    "Suparna Airlines",
    "Surinam Airways",
    "Swiss",
    "Syrian Air",
    "TAAG Angola Airlines",
    "TACA",
    "TACV Cabo Verde Airlines",
    "TAME Linea Aerea del Ecuador",
    "TAP Portugal",
    "TAROM",
    "Tassili Airlines",
    "Thai Airways International",
    "Thai Lion Air",
    "Thai Smile",
    "Tianjin Airlines",
    "TUI fly",
    "Turkish Airlines",
    "Tunisair",
    "T'way Air",
    "Ukraine International Airlines",
    "Uni Air",
    "UPS Airline",
    "Ural Airlines",
    "Urumqi Air",
    "UT Air",
    "Uzbekistan Airways",
    "Vietjet",
    "Vietnam Airlines",
    "Virgin Atlantic",
    "Virgin Australia",
    "Vistara",
    "Volaris Airline",
    "Volotea",
    "Vueling",
    "Wamos Air",
    "WDL Aviation",
    "WestJet",
    "White Airways",
    "Wideroe",
    "Xiamen Airline",
    "XL Airways",            
    ]


var select = document.getElementById('airlineopt');
var string;
for (var i = 0; i<airlines.length; i++){
 string+="<option value='"+airlines[i]+"'>"+airlines[i]+"</option>\n";

}
select.innerHTML=string;
